// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svjspwhozuftejoqmvqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2anNwd2hvenVmdGVqb3FtdnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NTA5ODEsImV4cCI6MjA4OTUyNjk4MX0.Z5YHmCmVhFK9kok6IeHbs3AMjAtNYWH9EHPgh193pMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});